name: Update Folder Log with Commit Dates

on:
  push:
    paths:
      - "**" # Trigger for all changes in the repository

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq (for JSON processing)
      run: sudo apt-get install -y jq

    - name: Update Folder Log with Commit Dates
      run: |
        # Path to the JSON file
        JSON_FILE="folder_log.json"

        # Check if the JSON file exists
        if [ ! -f "$JSON_FILE" ]; then
          echo "Error: JSON file '$JSON_FILE' not found."
          exit 1
        fi

        # Load the JSON data
        EXISTING_JSON=$(cat "$JSON_FILE")

        # Extract version folders from the JSON
        VERSION_FOLDERS=$(echo "$EXISTING_JSON" | jq -r '.versions[].version' | sed 's/^/versions\//')

        # Initialize updated JSON
        UPDATED_JSON=$(echo "$EXISTING_JSON" | jq '.')

        # Process each folder
        for FOLDER in $VERSION_FOLDERS; do
          if [ -d "$FOLDER" ]; then
            # Get the first and last commit dates
            FIRST_COMMIT_DATE=$(git log --reverse --format=%cs -- "$FOLDER" | head -n 1)
            LAST_COMMIT_DATE=$(git log -1 --format=%cs -- "$FOLDER")

            # Validate that we have both dates
            if [ -n "$FIRST_COMMIT_DATE" ] && [ -n "$LAST_COMMIT_DATE" ]; then
              VERSION=$(basename "$FOLDER")

              # Ensure release_date and last_updated keys exist
              UPDATED_JSON=$(echo "$UPDATED_JSON" | jq --arg version "$VERSION" --arg first "$FIRST_COMMIT_DATE" --arg last "$LAST_COMMIT_DATE" '
                .versions |= map(
                  if .version == $version then
                    .release_date = (if .release_date then .release_date else $first end) |
                    .last_updated = $last
                  else .
                  end
                )
              ')
            fi
          fi
        done

        # Write the updated JSON back to the file
        echo "$UPDATED_JSON" > "$JSON_FILE"

        # Commit and push the updated JSON file
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add "$JSON_FILE"
        git commit -m "Update folder log with commit dates"
        git push
